[package]
name = "rust-codespaces"
version = "0.1.0"
authors = ["Yakiyo"]
edition = "2018"

[dependencies]
clap = { version = "4.1.13", features = ["derive"] }
ureq = { version = "2.6.2", features = ["json"] }
