[package]
name = "dsm"
description = "Simplified version manager for the Dart SDK"
version = "0.1.0"
authors = ["Yakiyo <yakiyo1206@gmail.com>"]
edition = "2021"
license = "MIT"
repository = "https://github.com/Yakiyo/dsm"
homepage = "https://github.com/Yakiyo/dsm"

[dependencies]
anyhow = "1.0.71"
clap = { version = "3.2.25", features = ["derive", "env"] }
dart-semver = "0.1.3"
spinners = "4.1.0"
tempfile = "3.5.0"
ureq = "2.6.2"
yansi = "0.5.1"
zip = "0.6.5"

[target.'cfg(windows)'.dependencies]
junction = "1.0.0"

# Size optimizations. Reference: https://tauri.app/v1/guides/building/app-size/
[profile.release]
panic = "abort" # Strip expensive panic clean-up logic
codegen-units = 1 # Compile crates one after another so the compiler can optimize better
lto = true # Enables link to optimizations
strip = true # Remove debug symbols
