[package]
name = "dsm"
version = "0.1.0"
authors = ["Yakiyo"]
edition = "2018"

[dependencies]
clap = { version = "3.2.23", features = ["derive", "env"] }
ureq = { version = "2.6.2", features = ["json"] }
