name: ci

on: [ pull_request, push ]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Check 
        run: cargo check

      - name: Style Check
        run: cargo fmt --check